# Copyright (c) 2025 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "tracing-dlt"
version = "0.1.0"
edition.workspace = true
publish = false
description = "DLT log sink for "
homepage.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
# internal dependencies
dlt-rs = { workspace = true }

# external
tokio = { workspace = true }
indexmap = { workspace = true }

# logging & tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["registry"] }
tracing-core = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }

[features]
default = []
dlt_layer_internal_logging = []
trace_load_ctrl = ["dlt-rs/trace_load_ctrl"]
