# Copyright (c) 2025 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - v*

concurrency:
  group: "release-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  cargo-publish:
    permissions:
      content: read
    name: publish to crates.io
    # This will publish to crates.io if secrets.CRATES_TOKEN is set in the workspace, otherwise do a dry-run
    runs-on: ubuntu-latest
    env:
      CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain
        with:
          toolchain: 1.88.0
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - uses: ./.github/actions/setup-dlt
      - name: Publish to crates.io
        run: |
          # Determine publish arguments based on CRATES_API_TOKEN
          PUBLISH_ARGS="--all-features"
          if [ -z "$CRATES_API_TOKEN" ]; then
            PUBLISH_ARGS="$CRATES_API_TOKEN --dry-run"
            echo "CRATES_API_TOKEN is not set. Performing a dry-run publish for all crates."
          else
            PUBLISH_ARGS="$PUBLISH_ARGS --token ${CRATES_API_TOKEN}"
            echo "CRATES_API_TOKEN is set. Performing a real publish for all crates."
          fi

          echo "Attempting to publish dlt-sys..."
          (cd dlt-sys && cargo publish $PUBLISH_ARGS)
          echo "dlt-sys publish command executed."

          echo "Attempting to publish dlt-rs..."
          (cd dlt-rs && cargo publish $PUBLISH_ARGS)
          echo "dlt-rs publish command executed."

          echo "Attempting to publish tracing-dlt..."
          (cd tracing-dlt && cargo publish $PUBLISH_ARGS)
          echo "tracing-dlt publish command executed."
        env:
          RUSTFLAGS: "-L /usr/local/lib"
          PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
